### ISSUE TITLE
autoplay on video element isn't filtered out

### ISSUE THREAD

**Issue by g2p** [rubys/venus#1]
planet.gnome.org currently autoplays the video in this post: http://zaheer.merali.org/articles/2010/05/24/more-exciting-live-streaming-from-flumotion-with-vp8-and-webm/

Should this be fixed in planet venus, or in the feedparser?

**Comment by rubys** [comment]
I'm not seeing this with the latest venus:

<pre><code>$ python tests/reconstitute.py http://zaheer.merali.org/feed/ | grep '&lt;video'</code></pre>

<pre><code>&lt;p>&lt;video controls="controls" height="288" id="player" tabindex="0" width="512">&lt;br/></code></pre>
