### ISSUE TITLE
has this project moved off Github?  Is it deprecated?

### ISSUE THREAD

**Issue by dpocock** [rubys/venus#37]
There doesn't seem to be any activity in Github for a long time, is the project being maintained elsewhere?

The web site points to Github:
http://www.intertwingly.net/code/venus/planet/

If you are not maintaining the project, do you want somebody else to do so or is there a fork or official successor to the project?

**Comment by geraldb** [comment]
@dpocock  FYI There's an inofficial "successor" e.g. ground-up rewrite in Ruby called planet pluto e.g. works with a "standard" SQLite database for feeds and uses "simple" ERB for templates, for example. See -> https://github.com/feedreader Cheers.

**Comment by dpocock** [comment]
Thanks for pointing that out.

I started using planet-venus because it is available as a Debian package, I notice nobody has started to support a package for planet-pluto yet.
https://packages.qa.debian.org/p/planet-venus.html

There are a lot of people (myself included) who are much more familiar with Python than Ruby.  I wanted to add a line of code to enable syslog support (to stop sending log messages via cron emails), which is quite easy to do, but I notice that you haven't accepted any pull requests for a long time so I wasn't sure how I would release my change and get it back into Debian.

Do you think you may be willing to give anybody else access to the repository to accept pull requests and make releases or would you prefer that I make a fork of the project?

**Comment by geraldb** [comment]
@dpocock 

>  I started using planet-venus because it is available as a Debian package, 

 FYI: You can install planet pluto using the ruby package manager e.g.:

```
$ gem install pluto
```

Works great on Debian. Cheers. Good luck.

**Comment by dpocock** [comment]
Every project seems to be creating their own package manager these days.  Many of the sites I run for community projects are open source or non-profit, so I can't spend time supporting additional package managers on those systems, I just use things from the Debian stable (and backports) releases.

**Comment by geraldb** [comment]
@dpocock Not sure I understand. The additional "package manager" is just another program  and it comes with the ruby debian package, that's all. Anyways, good luck. I'd say you have to accept that this project is no longer maintained (e.g. last merge in 2011). Was just trying to help to point out something "better".

**Comment by dpocock** [comment]
I understand your point and I'm sure some people may be happy to use gem, pip, npm, maven and all those other package managers.  They are sometimes quite easy to use, but when you have so many different tools on the same system managing dependencies you can sometimes end up with more trouble later, especially if the security updates are not as fast as those from Debian.

For those who do want to keep using planet-venus for any reason, would you be happy to give somebody else control of the repository or point users to a new repository if I create one?

**Comment by anarcat** [comment]
I find planet pluto to be intriguing and interesting, even though it's not a real planet anymore. ;)

I would be interested in sharing maintenance as well. Seems to me people can just do it already: there's a ton of PRs to be merged in this queue, and even [patches in the Debian BTS](https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=planet-venus;tag=patch) waiting to be merged here...

The major issue with Venus, IMHO, is its dependency on 2.7 and httplib2: it would need to be ported to requests or something more modern to avoid [SNI bugs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813313) and the like.

**Comment by sanjayankur31** [comment]
@rubys - we have a few people here who wouldn't mind sharing the maintenance - do you think you can give them the required permissions please? Cheers!

**Comment by rubys** [comment]
It has not moved off of GitHub; it is not deprecated; but clearly it is not something I have been keeping on top of.  (It also is more mature/complete than pluto).

Who is still interested in maintaining this?  @anarcat clearly volunteered, but that was nearly a year ago now...

**Comment by sanjayankur31** [comment]
I can maybe help with the maintenance - pull requests and the sort, but I'd be a lot happier if folks like @anarcat took over the more important tasks such as development :)

**Comment by anarcat** [comment]
don't count on me too much... i don't have much time for this right now and will be away for a few weeks already. it'd be better if someone else would bottomline this. that being said, i'd be happy to unblock things (e.g. debian.org administrativia) if needs be. @rubys - at this point, i'd say share the access with any volunteer that steps up... worst case is you remove them. ;)

**Comment by Cabalist** [comment]
I am bumping this and saying I'd also be interested in help maintaining, porting to Py3, and  working through the backlog of pull requests.

**Comment by rubys** [comment]
@cabalist can I ask you to submit a few pull requests before I take you up on that offer?  If they look good, I'll add you as a collaborator.

**Comment by Cabalist** [comment]
No problem.  :)

**Comment by Cabalist** [comment]
Thanks @rubys !  I am working on getting this code running on Python3 and modernizing it.  Over the next few days I'll be trying to close the back log of pull requests and working on code coverage.  

This issue is closed
